env:
    browser: true
    es2021: true
extends:
    - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 13
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
rules:
    {
        indent: ["error", 4],
        "react/prop-types": 0,
        "max-len": 0,
        "import/extensions": 0,
        "import/no-unresolved": 0,
        "no-param-reassign": 0,
        "@typescript-eslint/no-unused-vars": [2, { "args": "none" }],
        "react/react-in-jsx-scope": 0,
        "react/jsx-indent": 0,
        "react/jsx-indent-props": 0,
        "react/jsx-filename-extension": [2, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
        "func-names": 0,
    }
